# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install SDK
    init: yarn install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: ignore

vscode:
  extensions:
    - prisma.prisma
    - graphql.vscode-graphql
    - esbenp.prettier-vscode
    - editorconfig.editorconfig
    - pflannery.vscode-versionlens
    - mgmcdermott.vscode-language-babel
    - bradlc.vscode-tailwindcss
    - jaspernorth.vscode-pigments
    - pkief.material-icon-theme
    - github.github-vscode-theme
    - mgmcdermott.vscode-language-babel

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
